'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.17929
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PrescriptionServiceReference
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="urn:Vidal", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="prescriptionAnalysis", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class prescriptionAnalysis
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private prescriptionLineAnalysisListField As PrescriptionServiceReference.ArrayOfPrescriptionLineAnalysis
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property prescriptionLineAnalysisList() As PrescriptionServiceReference.ArrayOfPrescriptionLineAnalysis
            Get
                Return Me.prescriptionLineAnalysisListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.prescriptionLineAnalysisListField, value) <> true) Then
                    Me.prescriptionLineAnalysisListField = value
                    Me.RaisePropertyChanged("prescriptionLineAnalysisList")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfPrescriptionLineAnalysis", [Namespace]:="urn:Vidal", ItemName:="prescriptionLineAnalysis"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfPrescriptionLineAnalysis
        Inherits System.Collections.Generic.List(Of PrescriptionServiceReference.prescriptionLineAnalysis)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="prescriptionLineAnalysis", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class prescriptionLineAnalysis
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private alertListField As PrescriptionServiceReference.ArrayOfAlert
        
        Private doseField As System.Nullable(Of Double)
        
        Private drugField As PrescriptionServiceReference.summarizedDrug
        
        Private durField As System.Nullable(Of Integer)
        
        Private durUnitField As System.Nullable(Of PrescriptionServiceReference.DurationType)
        
        Private posologyFrequencyField As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType)
        
        Private unitField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property alertList() As PrescriptionServiceReference.ArrayOfAlert
            Get
                Return Me.alertListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.alertListField, value) <> true) Then
                    Me.alertListField = value
                    Me.RaisePropertyChanged("alertList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property dose() As System.Nullable(Of Double)
            Get
                Return Me.doseField
            End Get
            Set
                If (Me.doseField.Equals(value) <> true) Then
                    Me.doseField = value
                    Me.RaisePropertyChanged("dose")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property drug() As PrescriptionServiceReference.summarizedDrug
            Get
                Return Me.drugField
            End Get
            Set
                If (Object.ReferenceEquals(Me.drugField, value) <> true) Then
                    Me.drugField = value
                    Me.RaisePropertyChanged("drug")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property dur() As System.Nullable(Of Integer)
            Get
                Return Me.durField
            End Get
            Set
                If (Me.durField.Equals(value) <> true) Then
                    Me.durField = value
                    Me.RaisePropertyChanged("dur")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property durUnit() As System.Nullable(Of PrescriptionServiceReference.DurationType)
            Get
                Return Me.durUnitField
            End Get
            Set
                If (Me.durUnitField.Equals(value) <> true) Then
                    Me.durUnitField = value
                    Me.RaisePropertyChanged("durUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property posologyFrequency() As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType)
            Get
                Return Me.posologyFrequencyField
            End Get
            Set
                If (Me.posologyFrequencyField.Equals(value) <> true) Then
                    Me.posologyFrequencyField = value
                    Me.RaisePropertyChanged("posologyFrequency")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property unit() As String
            Get
                Return Me.unitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.unitField, value) <> true) Then
                    Me.unitField = value
                    Me.RaisePropertyChanged("unit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="summarizedDrug", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class summarizedDrug
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        Private safetyAlertField As Boolean
        
        Private typeField As System.Nullable(Of PrescriptionServiceReference.DrugType)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property safetyAlert() As Boolean
            Get
                Return Me.safetyAlertField
            End Get
            Set
                If (Me.safetyAlertField.Equals(value) <> true) Then
                    Me.safetyAlertField = value
                    Me.RaisePropertyChanged("safetyAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property type() As System.Nullable(Of PrescriptionServiceReference.DrugType)
            Get
                Return Me.typeField
            End Get
            Set
                If (Me.typeField.Equals(value) <> true) Then
                    Me.typeField = value
                    Me.RaisePropertyChanged("type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfAlert", [Namespace]:="urn:Vidal", ItemName:="alert"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfAlert
        Inherits System.Collections.Generic.List(Of PrescriptionServiceReference.alert)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DurationType", [Namespace]:="urn:Vidal")>  _
    Public Enum DurationType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MINUTE = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HOUR = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DAY = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WEEK = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MONTH = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        YEAR = 5
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PosologyFrequencyType", [Namespace]:="urn:Vidal")>  _
    Public Enum PosologyFrequencyType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        THIS_DAY = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_DAY = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_24_HOURS = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_WEEK = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_MONTH = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_YEAR = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_2_DAYS = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_N_HOURS = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_HOUR = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PER_MINUTE = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TYPE_66 = 10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TYPE_46 = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TYPE_44 = 12
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="alert", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class alert
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private commentField As String
        
        Private referenceListField As PrescriptionServiceReference.ArrayOfReference
        
        Private relatedElementListField As PrescriptionServiceReference.ArrayOfRelatedElement
        
        Private severityField As System.Nullable(Of PrescriptionServiceReference.SeverityLevel)
        
        Private titleField As String
        
        Private typeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property comment() As String
            Get
                Return Me.commentField
            End Get
            Set
                If (Object.ReferenceEquals(Me.commentField, value) <> true) Then
                    Me.commentField = value
                    Me.RaisePropertyChanged("comment")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceList() As PrescriptionServiceReference.ArrayOfReference
            Get
                Return Me.referenceListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.referenceListField, value) <> true) Then
                    Me.referenceListField = value
                    Me.RaisePropertyChanged("referenceList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property relatedElementList() As PrescriptionServiceReference.ArrayOfRelatedElement
            Get
                Return Me.relatedElementListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.relatedElementListField, value) <> true) Then
                    Me.relatedElementListField = value
                    Me.RaisePropertyChanged("relatedElementList")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property severity() As System.Nullable(Of PrescriptionServiceReference.SeverityLevel)
            Get
                Return Me.severityField
            End Get
            Set
                If (Me.severityField.Equals(value) <> true) Then
                    Me.severityField = value
                    Me.RaisePropertyChanged("severity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.titleField, value) <> true) Then
                    Me.titleField = value
                    Me.RaisePropertyChanged("title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.typeField, value) <> true) Then
                    Me.typeField = value
                    Me.RaisePropertyChanged("type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfReference", [Namespace]:="urn:Vidal", ItemName:="reference"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfReference
        Inherits System.Collections.Generic.List(Of PrescriptionServiceReference.reference)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfRelatedElement", [Namespace]:="urn:Vidal", ItemName:="relatedElement"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfRelatedElement
        Inherits System.Collections.Generic.List(Of PrescriptionServiceReference.relatedElement)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SeverityLevel", [Namespace]:="urn:Vidal")>  _
    Public Enum SeverityLevel As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        INFO = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LEVEL_1 = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LEVEL_2 = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LEVEL_3 = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LEVEL_4 = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN = 5
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="reference", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class reference
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private referenceDateField As System.Nullable(Of Date)
        
        Private referenceNameField As String
        
        Private referenceTypeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceDate() As System.Nullable(Of Date)
            Get
                Return Me.referenceDateField
            End Get
            Set
                If (Me.referenceDateField.Equals(value) <> true) Then
                    Me.referenceDateField = value
                    Me.RaisePropertyChanged("referenceDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceName() As String
            Get
                Return Me.referenceNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.referenceNameField, value) <> true) Then
                    Me.referenceNameField = value
                    Me.RaisePropertyChanged("referenceName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceType() As String
            Get
                Return Me.referenceTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.referenceTypeField, value) <> true) Then
                    Me.referenceTypeField = value
                    Me.RaisePropertyChanged("referenceType")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="relatedElement", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class relatedElement
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private typeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property type() As String
            Get
                Return Me.typeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.typeField, value) <> true) Then
                    Me.typeField = value
                    Me.RaisePropertyChanged("type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DrugType", [Namespace]:="urn:Vidal")>  _
    Public Enum DrugType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        COMMON_NAME_GROUP = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PRODUCT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PACK = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UCD = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ACCESSORY_RANGE = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BRANDED_PRESCRIBABLE = 6
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DoseUnit", [Namespace]:="urn:Vidal")>  _
    Public Enum DoseUnit As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MG = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        G = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ML = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MCG = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        U = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        KU = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MU = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MMOL = 7
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfInt", [Namespace]:="urn:Vidal", ItemName:="int"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfInt
        Inherits System.Collections.Generic.List(Of System.Nullable(Of Integer))
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfAlertType", [Namespace]:="urn:Vidal", ItemName:="AlertType"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfAlertType
        Inherits System.Collections.Generic.List(Of System.Nullable(Of PrescriptionServiceReference.AlertType))
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AlertType", [Namespace]:="urn:Vidal")>  _
    Public Enum AlertType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PRECAUTION = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CONTRA_INDICATION = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ALLERGY = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        POSOLOGY = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PHYSICO_CHEMICAL_INTERACTION = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WARNING = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SIDE_EFFECT = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SURVEILLANCE = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        REDUNDANT_ACTIVE_INGREDIENT = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DRUG_INTERACTION = 9
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Gender", [Namespace]:="urn:Vidal")>  _
    Public Enum Gender As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MALE = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FEMALE = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Breastfeeding", [Namespace]:="urn:Vidal")>  _
    Public Enum Breastfeeding As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NONE = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LESS_THAN_ONE_MONTH = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MORE_THAN_ONE_MONTH = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ALL = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="HepaticInsufficiency", [Namespace]:="urn:Vidal")>  _
    Public Enum HepaticInsufficiency As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NONE = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MODERATE = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SEVERE = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="prescriptionCostAnalysis", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class prescriptionCostAnalysis
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private evaluatedPrescriptionLineCountField As Integer
        
        Private ignoredPrescriptionLineCountField As Integer
        
        Private maxPriceField As Single
        
        Private minPriceField As Single
        
        Private prescriptionLineCostListField As PrescriptionServiceReference.ArrayOfPrescriptionLineCost
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property evaluatedPrescriptionLineCount() As Integer
            Get
                Return Me.evaluatedPrescriptionLineCountField
            End Get
            Set
                If (Me.evaluatedPrescriptionLineCountField.Equals(value) <> true) Then
                    Me.evaluatedPrescriptionLineCountField = value
                    Me.RaisePropertyChanged("evaluatedPrescriptionLineCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ignoredPrescriptionLineCount() As Integer
            Get
                Return Me.ignoredPrescriptionLineCountField
            End Get
            Set
                If (Me.ignoredPrescriptionLineCountField.Equals(value) <> true) Then
                    Me.ignoredPrescriptionLineCountField = value
                    Me.RaisePropertyChanged("ignoredPrescriptionLineCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property maxPrice() As Single
            Get
                Return Me.maxPriceField
            End Get
            Set
                If (Me.maxPriceField.Equals(value) <> true) Then
                    Me.maxPriceField = value
                    Me.RaisePropertyChanged("maxPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property minPrice() As Single
            Get
                Return Me.minPriceField
            End Get
            Set
                If (Me.minPriceField.Equals(value) <> true) Then
                    Me.minPriceField = value
                    Me.RaisePropertyChanged("minPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property prescriptionLineCostList() As PrescriptionServiceReference.ArrayOfPrescriptionLineCost
            Get
                Return Me.prescriptionLineCostListField
            End Get
            Set
                If (Object.ReferenceEquals(Me.prescriptionLineCostListField, value) <> true) Then
                    Me.prescriptionLineCostListField = value
                    Me.RaisePropertyChanged("prescriptionLineCostList")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfPrescriptionLineCost", [Namespace]:="urn:Vidal", ItemName:="prescriptionLineCost"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfPrescriptionLineCost
        Inherits System.Collections.Generic.List(Of PrescriptionServiceReference.prescriptionLineCost)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="prescriptionLineCost", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class prescriptionLineCost
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private doseField As System.Nullable(Of Double)
        
        Private drugField As PrescriptionServiceReference.summarizedDrug
        
        Private durField As System.Nullable(Of Integer)
        
        Private durUnitField As System.Nullable(Of PrescriptionServiceReference.DurationType)
        
        Private posologyFrequencyField As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType)
        
        Private priceRangeField As PrescriptionServiceReference.priceRange
        
        Private unitField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property dose() As System.Nullable(Of Double)
            Get
                Return Me.doseField
            End Get
            Set
                If (Me.doseField.Equals(value) <> true) Then
                    Me.doseField = value
                    Me.RaisePropertyChanged("dose")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property drug() As PrescriptionServiceReference.summarizedDrug
            Get
                Return Me.drugField
            End Get
            Set
                If (Object.ReferenceEquals(Me.drugField, value) <> true) Then
                    Me.drugField = value
                    Me.RaisePropertyChanged("drug")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property dur() As System.Nullable(Of Integer)
            Get
                Return Me.durField
            End Get
            Set
                If (Me.durField.Equals(value) <> true) Then
                    Me.durField = value
                    Me.RaisePropertyChanged("dur")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property durUnit() As System.Nullable(Of PrescriptionServiceReference.DurationType)
            Get
                Return Me.durUnitField
            End Get
            Set
                If (Me.durUnitField.Equals(value) <> true) Then
                    Me.durUnitField = value
                    Me.RaisePropertyChanged("durUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property posologyFrequency() As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType)
            Get
                Return Me.posologyFrequencyField
            End Get
            Set
                If (Me.posologyFrequencyField.Equals(value) <> true) Then
                    Me.posologyFrequencyField = value
                    Me.RaisePropertyChanged("posologyFrequency")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property priceRange() As PrescriptionServiceReference.priceRange
            Get
                Return Me.priceRangeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.priceRangeField, value) <> true) Then
                    Me.priceRangeField = value
                    Me.RaisePropertyChanged("priceRange")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property unit() As String
            Get
                Return Me.unitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.unitField, value) <> true) Then
                    Me.unitField = value
                    Me.RaisePropertyChanged("unit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="priceRange", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class priceRange
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private maxPriceField As System.Nullable(Of Single)
        
        Private minPriceField As System.Nullable(Of Single)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property maxPrice() As System.Nullable(Of Single)
            Get
                Return Me.maxPriceField
            End Get
            Set
                If (Me.maxPriceField.Equals(value) <> true) Then
                    Me.maxPriceField = value
                    Me.RaisePropertyChanged("maxPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property minPrice() As System.Nullable(Of Single)
            Get
                Return Me.minPriceField
            End Get
            Set
                If (Me.minPriceField.Equals(value) <> true) Then
                    Me.minPriceField = value
                    Me.RaisePropertyChanged("minPrice")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DrugSummarizedAlertCouple", [Namespace]:="http://prescriptionAnalysis.api.vidal.com"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DrugSummarizedAlertCouple
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private summarizedAlertField As PrescriptionServiceReference.summarizedAlert
        
        Private summarizedDrugField As PrescriptionServiceReference.summarizedDrug
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property summarizedAlert() As PrescriptionServiceReference.summarizedAlert
            Get
                Return Me.summarizedAlertField
            End Get
            Set
                If (Object.ReferenceEquals(Me.summarizedAlertField, value) <> true) Then
                    Me.summarizedAlertField = value
                    Me.RaisePropertyChanged("summarizedAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property summarizedDrug() As PrescriptionServiceReference.summarizedDrug
            Get
                Return Me.summarizedDrugField
            End Get
            Set
                If (Object.ReferenceEquals(Me.summarizedDrugField, value) <> true) Then
                    Me.summarizedDrugField = value
                    Me.RaisePropertyChanged("summarizedDrug")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="summarizedAlert", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class summarizedAlert
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private allergiesAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedAllergyAlert)
        
        Private contraIndicationsAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedContraIndicationAlert)
        
        Private interactionsAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedInteractionAlert)
        
        Private physicoChemicalAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedPhysicoChemicalAlert)
        
        Private posologyAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedPosologyAlert)
        
        Private precautionsAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedPrecautionAlert)
        
        Private redundantInteractionsAlertField As System.Nullable(Of PrescriptionServiceReference.SummarizedRedundantInteractionAlert)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property allergiesAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedAllergyAlert)
            Get
                Return Me.allergiesAlertField
            End Get
            Set
                If (Me.allergiesAlertField.Equals(value) <> true) Then
                    Me.allergiesAlertField = value
                    Me.RaisePropertyChanged("allergiesAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property contraIndicationsAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedContraIndicationAlert)
            Get
                Return Me.contraIndicationsAlertField
            End Get
            Set
                If (Me.contraIndicationsAlertField.Equals(value) <> true) Then
                    Me.contraIndicationsAlertField = value
                    Me.RaisePropertyChanged("contraIndicationsAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property interactionsAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedInteractionAlert)
            Get
                Return Me.interactionsAlertField
            End Get
            Set
                If (Me.interactionsAlertField.Equals(value) <> true) Then
                    Me.interactionsAlertField = value
                    Me.RaisePropertyChanged("interactionsAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property physicoChemicalAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedPhysicoChemicalAlert)
            Get
                Return Me.physicoChemicalAlertField
            End Get
            Set
                If (Me.physicoChemicalAlertField.Equals(value) <> true) Then
                    Me.physicoChemicalAlertField = value
                    Me.RaisePropertyChanged("physicoChemicalAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property posologyAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedPosologyAlert)
            Get
                Return Me.posologyAlertField
            End Get
            Set
                If (Me.posologyAlertField.Equals(value) <> true) Then
                    Me.posologyAlertField = value
                    Me.RaisePropertyChanged("posologyAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property precautionsAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedPrecautionAlert)
            Get
                Return Me.precautionsAlertField
            End Get
            Set
                If (Me.precautionsAlertField.Equals(value) <> true) Then
                    Me.precautionsAlertField = value
                    Me.RaisePropertyChanged("precautionsAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property redundantInteractionsAlert() As System.Nullable(Of PrescriptionServiceReference.SummarizedRedundantInteractionAlert)
            Get
                Return Me.redundantInteractionsAlertField
            End Get
            Set
                If (Me.redundantInteractionsAlertField.Equals(value) <> true) Then
                    Me.redundantInteractionsAlertField = value
                    Me.RaisePropertyChanged("redundantInteractionsAlert")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedAllergyAlert", [Namespace]:="http://summerizedAlert.merlin.vidal.com")>  _
    Public Enum SummarizedAllergyAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HAS_ALERT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedContraIndicationAlert", [Namespace]:="urn:Vidal")>  _
    Public Enum SummarizedContraIndicationAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RELATIVE_ALERT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ABSOLUTE_ALERT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedInteractionAlert", [Namespace]:="http://summerizedAlert.merlin.vidal.com")>  _
    Public Enum SummarizedInteractionAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TAKE_INTO_ACCOUNT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PRECAUTION_USE = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DISADVISES_ASSOCIATION = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CONTRAINDICATIONS = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 5
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedPhysicoChemicalAlert", [Namespace]:="urn:Vidal")>  _
    Public Enum SummarizedPhysicoChemicalAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HAS_ALERT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedPosologyAlert", [Namespace]:="http://summerizedAlert.merlin.vidal.com")>  _
    Public Enum SummarizedPosologyAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HAS_ALERT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedPrecautionAlert", [Namespace]:="http://summerizedAlert.merlin.vidal.com")>  _
    Public Enum SummarizedPrecautionAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HAS_ALERT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SummarizedRedundantInteractionAlert", [Namespace]:="http://summerizedAlert.merlin.vidal.com")>  _
    Public Enum SummarizedRedundantInteractionAlert As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HAS_ALERT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NO_ALERT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        UNKNOWN_ALERT = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:Vidal", ConfigurationName:="PrescriptionServiceReference.drugPrescriptionAnalysisService")>  _
    Public Interface drugPrescriptionAnalysisService
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAlerts(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString) As <System.ServiceModel.MessageParameterAttribute(Name:="alerts")> PrescriptionServiceReference.prescriptionAnalysis
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function prescriptionLineInActivePrincipleDosesFromObjToJson(ByVal dose As System.Nullable(Of Double), ByVal doseUnit As System.Nullable(Of PrescriptionServiceReference.DoseUnit), ByVal frequencyType As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType), ByVal indicationIdList As PrescriptionServiceReference.ArrayOfInt, ByVal routeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal drugId As System.Nullable(Of Integer), ByVal drugType As System.Nullable(Of PrescriptionServiceReference.DrugType), ByVal duration As System.Nullable(Of Integer), ByVal durationType As System.Nullable(Of PrescriptionServiceReference.DurationType)) As <System.ServiceModel.MessageParameterAttribute(Name:="prescriptionLineInActivePrincipleDosesFromObjToJson")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAlertsWithoutAlertTypes(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString, ByVal withoutAlertTypes As PrescriptionServiceReference.ArrayOfAlertType) As <System.ServiceModel.MessageParameterAttribute(Name:="filteredAlerts")> PrescriptionServiceReference.prescriptionAnalysis
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAlertsAsHTML(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString) As <System.ServiceModel.MessageParameterAttribute(Name:="alertsAsHTML")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function prescriptionLineFromObjToJson(ByVal dose As System.Nullable(Of Double), ByVal unitId As System.Nullable(Of Integer), ByVal frequencyType As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType), ByVal indicationIdList As PrescriptionServiceReference.ArrayOfInt, ByVal routeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal drugId As System.Nullable(Of Integer), ByVal drugType As System.Nullable(Of PrescriptionServiceReference.DrugType)) As <System.ServiceModel.MessageParameterAttribute(Name:="prescriptionLineFromObjToJson")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function patientFromObjToJson(ByVal dateOfBirth As Date, ByVal gender As System.Nullable(Of PrescriptionServiceReference.Gender), ByVal weight As System.Nullable(Of Integer), ByVal height As System.Nullable(Of Integer), ByVal weeksOfAmenorrhea As System.Nullable(Of Integer), ByVal breastFeeding As System.Nullable(Of PrescriptionServiceReference.Breastfeeding), ByVal creatin As System.Nullable(Of Integer), ByVal hepaticInsufficiency As System.Nullable(Of PrescriptionServiceReference.HepaticInsufficiency), ByVal allergyIdList As PrescriptionServiceReference.ArrayOfInt, ByVal moleculeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal pathologyCim10IdList As PrescriptionServiceReference.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="patientFromObjToJson")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function prescriptionLineInDosesFromObjToJson(ByVal dose As System.Nullable(Of Double), ByVal unitId As System.Nullable(Of Integer), ByVal frequencyType As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType), ByVal indicationIdList As PrescriptionServiceReference.ArrayOfInt, ByVal routeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal drugId As System.Nullable(Of Integer), ByVal drugType As System.Nullable(Of PrescriptionServiceReference.DrugType), ByVal duration As System.Nullable(Of Integer), ByVal durationType As System.Nullable(Of PrescriptionServiceReference.DurationType)) As <System.ServiceModel.MessageParameterAttribute(Name:="prescriptionLineInDosesFromObjToJson")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getPrescriptionCostAnalysis(ByVal prescriptionLines As PrescriptionServiceReference.ArrayOfString) As <System.ServiceModel.MessageParameterAttribute(Name:="prescriptionCostAnalysis")> PrescriptionServiceReference.prescriptionCostAnalysis
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getSummarizedAlert(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString) As <System.ServiceModel.MessageParameterAttribute(Name:="summarizedAlert")> PrescriptionServiceReference.DrugSummarizedAlertCouple()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface drugPrescriptionAnalysisServiceChannel
        Inherits PrescriptionServiceReference.drugPrescriptionAnalysisService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class drugPrescriptionAnalysisServiceClient
        Inherits System.ServiceModel.ClientBase(Of PrescriptionServiceReference.drugPrescriptionAnalysisService)
        Implements PrescriptionServiceReference.drugPrescriptionAnalysisService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function getAlerts(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString) As PrescriptionServiceReference.prescriptionAnalysis Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.getAlerts
            Return MyBase.Channel.getAlerts(patient, prescriptionLineList)
        End Function
        
        Public Function prescriptionLineInActivePrincipleDosesFromObjToJson(ByVal dose As System.Nullable(Of Double), ByVal doseUnit As System.Nullable(Of PrescriptionServiceReference.DoseUnit), ByVal frequencyType As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType), ByVal indicationIdList As PrescriptionServiceReference.ArrayOfInt, ByVal routeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal drugId As System.Nullable(Of Integer), ByVal drugType As System.Nullable(Of PrescriptionServiceReference.DrugType), ByVal duration As System.Nullable(Of Integer), ByVal durationType As System.Nullable(Of PrescriptionServiceReference.DurationType)) As String Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.prescriptionLineInActivePrincipleDosesFromObjToJson
            Return MyBase.Channel.prescriptionLineInActivePrincipleDosesFromObjToJson(dose, doseUnit, frequencyType, indicationIdList, routeIdList, drugId, drugType, duration, durationType)
        End Function
        
        Public Function getAlertsWithoutAlertTypes(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString, ByVal withoutAlertTypes As PrescriptionServiceReference.ArrayOfAlertType) As PrescriptionServiceReference.prescriptionAnalysis Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.getAlertsWithoutAlertTypes
            Return MyBase.Channel.getAlertsWithoutAlertTypes(patient, prescriptionLineList, withoutAlertTypes)
        End Function
        
        Public Function getAlertsAsHTML(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString) As String Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.getAlertsAsHTML
            Return MyBase.Channel.getAlertsAsHTML(patient, prescriptionLineList)
        End Function
        
        Public Function prescriptionLineFromObjToJson(ByVal dose As System.Nullable(Of Double), ByVal unitId As System.Nullable(Of Integer), ByVal frequencyType As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType), ByVal indicationIdList As PrescriptionServiceReference.ArrayOfInt, ByVal routeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal drugId As System.Nullable(Of Integer), ByVal drugType As System.Nullable(Of PrescriptionServiceReference.DrugType)) As String Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.prescriptionLineFromObjToJson
            Return MyBase.Channel.prescriptionLineFromObjToJson(dose, unitId, frequencyType, indicationIdList, routeIdList, drugId, drugType)
        End Function
        
        Public Function patientFromObjToJson(ByVal dateOfBirth As Date, ByVal gender As System.Nullable(Of PrescriptionServiceReference.Gender), ByVal weight As System.Nullable(Of Integer), ByVal height As System.Nullable(Of Integer), ByVal weeksOfAmenorrhea As System.Nullable(Of Integer), ByVal breastFeeding As System.Nullable(Of PrescriptionServiceReference.Breastfeeding), ByVal creatin As System.Nullable(Of Integer), ByVal hepaticInsufficiency As System.Nullable(Of PrescriptionServiceReference.HepaticInsufficiency), ByVal allergyIdList As PrescriptionServiceReference.ArrayOfInt, ByVal moleculeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal pathologyCim10IdList As PrescriptionServiceReference.ArrayOfInt) As String Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.patientFromObjToJson
            Return MyBase.Channel.patientFromObjToJson(dateOfBirth, gender, weight, height, weeksOfAmenorrhea, breastFeeding, creatin, hepaticInsufficiency, allergyIdList, moleculeIdList, pathologyCim10IdList)
        End Function
        
        Public Function prescriptionLineInDosesFromObjToJson(ByVal dose As System.Nullable(Of Double), ByVal unitId As System.Nullable(Of Integer), ByVal frequencyType As System.Nullable(Of PrescriptionServiceReference.PosologyFrequencyType), ByVal indicationIdList As PrescriptionServiceReference.ArrayOfInt, ByVal routeIdList As PrescriptionServiceReference.ArrayOfInt, ByVal drugId As System.Nullable(Of Integer), ByVal drugType As System.Nullable(Of PrescriptionServiceReference.DrugType), ByVal duration As System.Nullable(Of Integer), ByVal durationType As System.Nullable(Of PrescriptionServiceReference.DurationType)) As String Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.prescriptionLineInDosesFromObjToJson
            Return MyBase.Channel.prescriptionLineInDosesFromObjToJson(dose, unitId, frequencyType, indicationIdList, routeIdList, drugId, drugType, duration, durationType)
        End Function
        
        Public Function getPrescriptionCostAnalysis(ByVal prescriptionLines As PrescriptionServiceReference.ArrayOfString) As PrescriptionServiceReference.prescriptionCostAnalysis Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.getPrescriptionCostAnalysis
            Return MyBase.Channel.getPrescriptionCostAnalysis(prescriptionLines)
        End Function
        
        Public Function getSummarizedAlert(ByVal patient As String, ByVal prescriptionLineList As PrescriptionServiceReference.ArrayOfString) As PrescriptionServiceReference.DrugSummarizedAlertCouple() Implements PrescriptionServiceReference.drugPrescriptionAnalysisService.getSummarizedAlert
            Return MyBase.Channel.getSummarizedAlert(patient, prescriptionLineList)
        End Function
    End Class
End Namespace
