'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.17929
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace VidalUcdService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfInt", [Namespace]:="urn:Vidal", ItemName:="int"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfInt
        Inherits System.Collections.Generic.List(Of System.Nullable(Of Integer))
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUcd", [Namespace]:="urn:Vidal", ItemName:="ucd"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUcd
        Inherits System.Collections.Generic.List(Of VidalUcdService.ucd)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ucd", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ucd
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private codeField As String
        
        Private code13Field As String
        
        Private ghsField As Boolean
        
        Private ghsPriceField As System.Nullable(Of Single)
        
        Private idField As System.Nullable(Of Integer)
        
        Private marketStatusField As System.Nullable(Of VidalUcdService.MarketStatus)
        
        Private maxUcdRangePriceField As System.Nullable(Of Single)
        
        Private minUcdRangePriceField As System.Nullable(Of Single)
        
        Private nameField As String
        
        Private retrocessionField As Boolean
        
        Private retrocessionPriceField As System.Nullable(Of Single)
        
        Private safetyAlertField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codeField, value) <> true) Then
                    Me.codeField = value
                    Me.RaisePropertyChanged("code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code13() As String
            Get
                Return Me.code13Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.code13Field, value) <> true) Then
                    Me.code13Field = value
                    Me.RaisePropertyChanged("code13")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghs() As Boolean
            Get
                Return Me.ghsField
            End Get
            Set
                If (Me.ghsField.Equals(value) <> true) Then
                    Me.ghsField = value
                    Me.RaisePropertyChanged("ghs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghsPrice() As System.Nullable(Of Single)
            Get
                Return Me.ghsPriceField
            End Get
            Set
                If (Me.ghsPriceField.Equals(value) <> true) Then
                    Me.ghsPriceField = value
                    Me.RaisePropertyChanged("ghsPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property marketStatus() As System.Nullable(Of VidalUcdService.MarketStatus)
            Get
                Return Me.marketStatusField
            End Get
            Set
                If (Me.marketStatusField.Equals(value) <> true) Then
                    Me.marketStatusField = value
                    Me.RaisePropertyChanged("marketStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property maxUcdRangePrice() As System.Nullable(Of Single)
            Get
                Return Me.maxUcdRangePriceField
            End Get
            Set
                If (Me.maxUcdRangePriceField.Equals(value) <> true) Then
                    Me.maxUcdRangePriceField = value
                    Me.RaisePropertyChanged("maxUcdRangePrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property minUcdRangePrice() As System.Nullable(Of Single)
            Get
                Return Me.minUcdRangePriceField
            End Get
            Set
                If (Me.minUcdRangePriceField.Equals(value) <> true) Then
                    Me.minUcdRangePriceField = value
                    Me.RaisePropertyChanged("minUcdRangePrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocession() As Boolean
            Get
                Return Me.retrocessionField
            End Get
            Set
                If (Me.retrocessionField.Equals(value) <> true) Then
                    Me.retrocessionField = value
                    Me.RaisePropertyChanged("retrocession")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocessionPrice() As System.Nullable(Of Single)
            Get
                Return Me.retrocessionPriceField
            End Get
            Set
                If (Me.retrocessionPriceField.Equals(value) <> true) Then
                    Me.retrocessionPriceField = value
                    Me.RaisePropertyChanged("retrocessionPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property safetyAlert() As Boolean
            Get
                Return Me.safetyAlertField
            End Get
            Set
                If (Me.safetyAlertField.Equals(value) <> true) Then
                    Me.safetyAlertField = value
                    Me.RaisePropertyChanged("safetyAlert")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MarketStatus", [Namespace]:="urn:Vidal")>  _
    Public Enum MarketStatus As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AVAILABLE = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DELETED = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PHARMACO = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [NEW] = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DELETED_ONEYEAR = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        PHARMACO_ONEYEAR = 5
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UcdApiFilter", [Namespace]:="urn:Vidal")>  _
    Public Enum UcdApiFilter As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ALL = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HORSGHS = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RETROCESSION = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfMarketStatus", [Namespace]:="urn:Vidal", ItemName:="MarketStatus"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfMarketStatus
        Inherits System.Collections.Generic.List(Of System.Nullable(Of VidalUcdService.MarketStatus))
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="pagedResultUcd", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class pagedResultUcd
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private pageNumberField As Integer
        
        Private pageSizeField As Integer
        
        Private resultField As VidalUcdService.ArrayOfUcd
        
        Private rowCountField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property pageNumber() As Integer
            Get
                Return Me.pageNumberField
            End Get
            Set
                If (Me.pageNumberField.Equals(value) <> true) Then
                    Me.pageNumberField = value
                    Me.RaisePropertyChanged("pageNumber")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property pageSize() As Integer
            Get
                Return Me.pageSizeField
            End Get
            Set
                If (Me.pageSizeField.Equals(value) <> true) Then
                    Me.pageSizeField = value
                    Me.RaisePropertyChanged("pageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property result() As VidalUcdService.ArrayOfUcd
            Get
                Return Me.resultField
            End Get
            Set
                If (Object.ReferenceEquals(Me.resultField, value) <> true) Then
                    Me.resultField = value
                    Me.RaisePropertyChanged("result")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property rowCount() As Integer
            Get
                Return Me.rowCountField
            End Get
            Set
                If (Me.rowCountField.Equals(value) <> true) Then
                    Me.rowCountField = value
                    Me.RaisePropertyChanged("rowCount")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfProductRangeUcdCouple", [Namespace]:="urn:Vidal", ItemName:="productRangeUcdCouple"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfProductRangeUcdCouple
        Inherits System.Collections.Generic.List(Of VidalUcdService.productRangeUcdCouple)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="productRangeUcdCouple", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class productRangeUcdCouple
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private productRangeField As VidalUcdService.productRange
        
        Private ucdField As VidalUcdService.ucd
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property productRange() As VidalUcdService.productRange
            Get
                Return Me.productRangeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.productRangeField, value) <> true) Then
                    Me.productRangeField = value
                    Me.RaisePropertyChanged("productRange")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucd() As VidalUcdService.ucd
            Get
                Return Me.ucdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ucdField, value) <> true) Then
                    Me.ucdField = value
                    Me.RaisePropertyChanged("ucd")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="productRange", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class productRange
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="urn:Vidal", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompanyType", [Namespace]:="urn:Vidal")>  _
    Public Enum CompanyType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OWNER = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        HOLDER = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DISTRIBUTOR = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SUBSCRIBER = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfBrandedPrescribableUcds", [Namespace]:="urn:Vidal", ItemName:="brandedPrescribableUcds"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfBrandedPrescribableUcds
        Inherits System.Collections.Generic.List(Of VidalUcdService.brandedPrescribableUcds)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="brandedPrescribableUcds", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class brandedPrescribableUcds
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private brandedPrescribableField As VidalUcdService.brandedPrescribable
        
        Private ucdsField As VidalUcdService.ArrayOfUcd
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property brandedPrescribable() As VidalUcdService.brandedPrescribable
            Get
                Return Me.brandedPrescribableField
            End Get
            Set
                If (Object.ReferenceEquals(Me.brandedPrescribableField, value) <> true) Then
                    Me.brandedPrescribableField = value
                    Me.RaisePropertyChanged("brandedPrescribable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucds() As VidalUcdService.ArrayOfUcd
            Get
                Return Me.ucdsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ucdsField, value) <> true) Then
                    Me.ucdsField = value
                    Me.RaisePropertyChanged("ucds")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="brandedPrescribable", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class brandedPrescribable
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private codeField As String
        
        Private hasKnownEffectExcipientsField As System.Nullable(Of Boolean)
        
        Private homogeneousOnIndicationsField As System.Nullable(Of Boolean)
        
        Private idField As System.Nullable(Of Integer)
        
        Private multipleRoutesField As System.Nullable(Of Boolean)
        
        Private nameField As String
        
        Private safetyAlertField As System.Nullable(Of Boolean)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codeField, value) <> true) Then
                    Me.codeField = value
                    Me.RaisePropertyChanged("code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property hasKnownEffectExcipients() As System.Nullable(Of Boolean)
            Get
                Return Me.hasKnownEffectExcipientsField
            End Get
            Set
                If (Me.hasKnownEffectExcipientsField.Equals(value) <> true) Then
                    Me.hasKnownEffectExcipientsField = value
                    Me.RaisePropertyChanged("hasKnownEffectExcipients")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property homogeneousOnIndications() As System.Nullable(Of Boolean)
            Get
                Return Me.homogeneousOnIndicationsField
            End Get
            Set
                If (Me.homogeneousOnIndicationsField.Equals(value) <> true) Then
                    Me.homogeneousOnIndicationsField = value
                    Me.RaisePropertyChanged("homogeneousOnIndications")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property multipleRoutes() As System.Nullable(Of Boolean)
            Get
                Return Me.multipleRoutesField
            End Get
            Set
                If (Me.multipleRoutesField.Equals(value) <> true) Then
                    Me.multipleRoutesField = value
                    Me.RaisePropertyChanged("multipleRoutes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property safetyAlert() As System.Nullable(Of Boolean)
            Get
                Return Me.safetyAlertField
            End Get
            Set
                If (Me.safetyAlertField.Equals(value) <> true) Then
                    Me.safetyAlertField = value
                    Me.RaisePropertyChanged("safetyAlert")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUcdIndicators", [Namespace]:="urn:Vidal", ItemName:="ucdIndicators"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUcdIndicators
        Inherits System.Collections.Generic.List(Of VidalUcdService.ucdIndicators)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ucdIndicators", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ucdIndicators
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private codeField As String
        
        Private code13Field As String
        
        Private ghsField As Boolean
        
        Private ghsPriceField As System.Nullable(Of Single)
        
        Private idField As System.Nullable(Of Integer)
        
        Private indicatorsField As VidalUcdService.ArrayOfIndicator
        
        Private marketStatusField As System.Nullable(Of VidalUcdService.MarketStatus)
        
        Private nameField As String
        
        Private retrocessionField As Boolean
        
        Private retrocessionPriceField As System.Nullable(Of Single)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codeField, value) <> true) Then
                    Me.codeField = value
                    Me.RaisePropertyChanged("code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code13() As String
            Get
                Return Me.code13Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.code13Field, value) <> true) Then
                    Me.code13Field = value
                    Me.RaisePropertyChanged("code13")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghs() As Boolean
            Get
                Return Me.ghsField
            End Get
            Set
                If (Me.ghsField.Equals(value) <> true) Then
                    Me.ghsField = value
                    Me.RaisePropertyChanged("ghs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghsPrice() As System.Nullable(Of Single)
            Get
                Return Me.ghsPriceField
            End Get
            Set
                If (Me.ghsPriceField.Equals(value) <> true) Then
                    Me.ghsPriceField = value
                    Me.RaisePropertyChanged("ghsPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property indicators() As VidalUcdService.ArrayOfIndicator
            Get
                Return Me.indicatorsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.indicatorsField, value) <> true) Then
                    Me.indicatorsField = value
                    Me.RaisePropertyChanged("indicators")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property marketStatus() As System.Nullable(Of VidalUcdService.MarketStatus)
            Get
                Return Me.marketStatusField
            End Get
            Set
                If (Me.marketStatusField.Equals(value) <> true) Then
                    Me.marketStatusField = value
                    Me.RaisePropertyChanged("marketStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocession() As Boolean
            Get
                Return Me.retrocessionField
            End Get
            Set
                If (Me.retrocessionField.Equals(value) <> true) Then
                    Me.retrocessionField = value
                    Me.RaisePropertyChanged("retrocession")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocessionPrice() As System.Nullable(Of Single)
            Get
                Return Me.retrocessionPriceField
            End Get
            Set
                If (Me.retrocessionPriceField.Equals(value) <> true) Then
                    Me.retrocessionPriceField = value
                    Me.RaisePropertyChanged("retrocessionPrice")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfIndicator", [Namespace]:="urn:Vidal", ItemName:="indicator"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfIndicator
        Inherits System.Collections.Generic.List(Of VidalUcdService.indicator)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="indicator", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class indicator
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private indicatorValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property indicatorValue() As String
            Get
                Return Me.indicatorValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.indicatorValueField, value) <> true) Then
                    Me.indicatorValueField = value
                    Me.RaisePropertyChanged("indicatorValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUcdPosologyUnitsAndItemsConcentrations", [Namespace]:="urn:Vidal", ItemName:="ucdPosologyUnitsAndItemsConcentrations"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUcdPosologyUnitsAndItemsConcentrations
        Inherits System.Collections.Generic.List(Of VidalUcdService.ucdPosologyUnitsAndItemsConcentrations)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ucdPosologyUnitsAndItemsConcentrations", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ucdPosologyUnitsAndItemsConcentrations
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private codeField As String
        
        Private code13Field As String
        
        Private ghsField As Boolean
        
        Private ghsEffectiveDateField As System.Nullable(Of Date)
        
        Private ghsPriceField As System.Nullable(Of Single)
        
        Private idField As System.Nullable(Of Integer)
        
        Private marketStatusField As System.Nullable(Of VidalUcdService.MarketStatus)
        
        Private nameField As String
        
        Private retrocessionField As Boolean
        
        Private retrocessionEffectiveDateField As System.Nullable(Of Date)
        
        Private retrocessionPriceField As System.Nullable(Of Single)
        
        Private ucdItemsField As VidalUcdService.ArrayOfUcdItem
        
        Private ucdPosologyUnitsField As VidalUcdService.ArrayOfUcdPosologyUnit
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codeField, value) <> true) Then
                    Me.codeField = value
                    Me.RaisePropertyChanged("code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property code13() As String
            Get
                Return Me.code13Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.code13Field, value) <> true) Then
                    Me.code13Field = value
                    Me.RaisePropertyChanged("code13")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghs() As Boolean
            Get
                Return Me.ghsField
            End Get
            Set
                If (Me.ghsField.Equals(value) <> true) Then
                    Me.ghsField = value
                    Me.RaisePropertyChanged("ghs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghsEffectiveDate() As System.Nullable(Of Date)
            Get
                Return Me.ghsEffectiveDateField
            End Get
            Set
                If (Me.ghsEffectiveDateField.Equals(value) <> true) Then
                    Me.ghsEffectiveDateField = value
                    Me.RaisePropertyChanged("ghsEffectiveDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ghsPrice() As System.Nullable(Of Single)
            Get
                Return Me.ghsPriceField
            End Get
            Set
                If (Me.ghsPriceField.Equals(value) <> true) Then
                    Me.ghsPriceField = value
                    Me.RaisePropertyChanged("ghsPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property marketStatus() As System.Nullable(Of VidalUcdService.MarketStatus)
            Get
                Return Me.marketStatusField
            End Get
            Set
                If (Me.marketStatusField.Equals(value) <> true) Then
                    Me.marketStatusField = value
                    Me.RaisePropertyChanged("marketStatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocession() As Boolean
            Get
                Return Me.retrocessionField
            End Get
            Set
                If (Me.retrocessionField.Equals(value) <> true) Then
                    Me.retrocessionField = value
                    Me.RaisePropertyChanged("retrocession")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocessionEffectiveDate() As System.Nullable(Of Date)
            Get
                Return Me.retrocessionEffectiveDateField
            End Get
            Set
                If (Me.retrocessionEffectiveDateField.Equals(value) <> true) Then
                    Me.retrocessionEffectiveDateField = value
                    Me.RaisePropertyChanged("retrocessionEffectiveDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property retrocessionPrice() As System.Nullable(Of Single)
            Get
                Return Me.retrocessionPriceField
            End Get
            Set
                If (Me.retrocessionPriceField.Equals(value) <> true) Then
                    Me.retrocessionPriceField = value
                    Me.RaisePropertyChanged("retrocessionPrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucdItems() As VidalUcdService.ArrayOfUcdItem
            Get
                Return Me.ucdItemsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ucdItemsField, value) <> true) Then
                    Me.ucdItemsField = value
                    Me.RaisePropertyChanged("ucdItems")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucdPosologyUnits() As VidalUcdService.ArrayOfUcdPosologyUnit
            Get
                Return Me.ucdPosologyUnitsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ucdPosologyUnitsField, value) <> true) Then
                    Me.ucdPosologyUnitsField = value
                    Me.RaisePropertyChanged("ucdPosologyUnits")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUcdItem", [Namespace]:="urn:Vidal", ItemName:="ucdItem"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUcdItem
        Inherits System.Collections.Generic.List(Of VidalUcdService.ucdItem)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUcdPosologyUnit", [Namespace]:="urn:Vidal", ItemName:="ucdPosologyUnit"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUcdPosologyUnit
        Inherits System.Collections.Generic.List(Of VidalUcdService.ucdPosologyUnit)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ucdItem", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ucdItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private activeSubstanceInformationsField As VidalUcdService.ArrayOfActiveSubstanceInformation
        
        Private fullNameField As String
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property activeSubstanceInformations() As VidalUcdService.ArrayOfActiveSubstanceInformation
            Get
                Return Me.activeSubstanceInformationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.activeSubstanceInformationsField, value) <> true) Then
                    Me.activeSubstanceInformationsField = value
                    Me.RaisePropertyChanged("activeSubstanceInformations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property fullName() As String
            Get
                Return Me.fullNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fullNameField, value) <> true) Then
                    Me.fullNameField = value
                    Me.RaisePropertyChanged("fullName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfActiveSubstanceInformation", [Namespace]:="urn:Vidal", ItemName:="activeSubstanceInformation"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfActiveSubstanceInformation
        Inherits System.Collections.Generic.List(Of VidalUcdService.activeSubstanceInformation)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="activeSubstanceInformation", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class activeSubstanceInformation
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private concentrationUnitField As VidalUcdService.posologyUnit
        
        Private concentrationValueField As System.Nullable(Of Single)
        
        Private moleculeField As VidalUcdService.molecule
        
        Private quantityField As System.Nullable(Of Single)
        
        Private quantityUnitField As VidalUcdService.posologyUnit
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property concentrationUnit() As VidalUcdService.posologyUnit
            Get
                Return Me.concentrationUnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.concentrationUnitField, value) <> true) Then
                    Me.concentrationUnitField = value
                    Me.RaisePropertyChanged("concentrationUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property concentrationValue() As System.Nullable(Of Single)
            Get
                Return Me.concentrationValueField
            End Get
            Set
                If (Me.concentrationValueField.Equals(value) <> true) Then
                    Me.concentrationValueField = value
                    Me.RaisePropertyChanged("concentrationValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property molecule() As VidalUcdService.molecule
            Get
                Return Me.moleculeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.moleculeField, value) <> true) Then
                    Me.moleculeField = value
                    Me.RaisePropertyChanged("molecule")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property quantity() As System.Nullable(Of Single)
            Get
                Return Me.quantityField
            End Get
            Set
                If (Me.quantityField.Equals(value) <> true) Then
                    Me.quantityField = value
                    Me.RaisePropertyChanged("quantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property quantityUnit() As VidalUcdService.posologyUnit
            Get
                Return Me.quantityUnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.quantityUnitField, value) <> true) Then
                    Me.quantityUnitField = value
                    Me.RaisePropertyChanged("quantityUnit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="posologyUnit", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class posologyUnit
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="molecule", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class molecule
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private allergyAlertField As Boolean
        
        Private homeopathyField As Boolean
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        Private roleField As System.Nullable(Of VidalUcdService.SubstanceRole)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property allergyAlert() As Boolean
            Get
                Return Me.allergyAlertField
            End Get
            Set
                If (Me.allergyAlertField.Equals(value) <> true) Then
                    Me.allergyAlertField = value
                    Me.RaisePropertyChanged("allergyAlert")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property homeopathy() As Boolean
            Get
                Return Me.homeopathyField
            End Get
            Set
                If (Me.homeopathyField.Equals(value) <> true) Then
                    Me.homeopathyField = value
                    Me.RaisePropertyChanged("homeopathy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property role() As System.Nullable(Of VidalUcdService.SubstanceRole)
            Get
                Return Me.roleField
            End Get
            Set
                If (Me.roleField.Equals(value) <> true) Then
                    Me.roleField = value
                    Me.RaisePropertyChanged("role")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SubstanceRole", [Namespace]:="urn:Vidal")>  _
    Public Enum SubstanceRole As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ACTIVE_PRINCIPLE_OR_EXCIPIENT = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EXCIPIENT = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ACTIVE_PRINCIPLE = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ucdPosologyUnit", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ucdPosologyUnit
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private dispensingUnitField As VidalUcdService.posologyUnit
        
        Private posologyUnitField As VidalUcdService.posologyUnit
        
        Private ratioOfPosologyUnitOverDispensingUnitField As System.Nullable(Of Single)
        
        Private ucdItemQuantityField As System.Nullable(Of Single)
        
        Private ucdItemQuantityUnitField As VidalUcdService.posologyUnit
        
        Private ucdItemVolumeField As System.Nullable(Of Single)
        
        Private ucdItemVolumeUnitField As VidalUcdService.posologyUnit
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property dispensingUnit() As VidalUcdService.posologyUnit
            Get
                Return Me.dispensingUnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.dispensingUnitField, value) <> true) Then
                    Me.dispensingUnitField = value
                    Me.RaisePropertyChanged("dispensingUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property posologyUnit() As VidalUcdService.posologyUnit
            Get
                Return Me.posologyUnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.posologyUnitField, value) <> true) Then
                    Me.posologyUnitField = value
                    Me.RaisePropertyChanged("posologyUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ratioOfPosologyUnitOverDispensingUnit() As System.Nullable(Of Single)
            Get
                Return Me.ratioOfPosologyUnitOverDispensingUnitField
            End Get
            Set
                If (Me.ratioOfPosologyUnitOverDispensingUnitField.Equals(value) <> true) Then
                    Me.ratioOfPosologyUnitOverDispensingUnitField = value
                    Me.RaisePropertyChanged("ratioOfPosologyUnitOverDispensingUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucdItemQuantity() As System.Nullable(Of Single)
            Get
                Return Me.ucdItemQuantityField
            End Get
            Set
                If (Me.ucdItemQuantityField.Equals(value) <> true) Then
                    Me.ucdItemQuantityField = value
                    Me.RaisePropertyChanged("ucdItemQuantity")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucdItemQuantityUnit() As VidalUcdService.posologyUnit
            Get
                Return Me.ucdItemQuantityUnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ucdItemQuantityUnitField, value) <> true) Then
                    Me.ucdItemQuantityUnitField = value
                    Me.RaisePropertyChanged("ucdItemQuantityUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucdItemVolume() As System.Nullable(Of Single)
            Get
                Return Me.ucdItemVolumeField
            End Get
            Set
                If (Me.ucdItemVolumeField.Equals(value) <> true) Then
                    Me.ucdItemVolumeField = value
                    Me.RaisePropertyChanged("ucdItemVolume")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property ucdItemVolumeUnit() As VidalUcdService.posologyUnit
            Get
                Return Me.ucdItemVolumeUnitField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ucdItemVolumeUnitField, value) <> true) Then
                    Me.ucdItemVolumeUnitField = value
                    Me.RaisePropertyChanged("ucdItemVolumeUnit")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:Vidal", ConfigurationName:="VidalUcdService.ucdService")>  _
    Public Interface ucdService
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByIds(ByVal ucdIds As VidalUcdService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getAllUcds(ByVal ucdApiFilter As System.Nullable(Of VidalUcdService.UcdApiFilter), ByVal marketStatuses As VidalUcdService.ArrayOfMarketStatus, ByVal pageNumber As System.Nullable(Of Integer), ByVal pageSize As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="pagedResultUcd")> VidalUcdService.pagedResultUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByProductRangeIds(ByVal productRangeIds As VidalUcdService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="ProductRangeUcdCoupleList")> VidalUcdService.ArrayOfProductRangeUcdCouple
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByProductId(ByVal productId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByCommonNameGroupId(ByVal commonNameGroupId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchById(ByVal ucdId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="ucd")> VidalUcdService.ucd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByCodes(ByVal codes As VidalUcdService.ArrayOfString) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchNewlyAvailableUcds() As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByCode(ByVal code As String) As <System.ServiceModel.MessageParameterAttribute(Name:="ucd")> VidalUcdService.ucd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByCompanyIdAndType(ByVal companyId As System.Nullable(Of Integer), ByVal type As System.Nullable(Of VidalUcdService.CompanyType)) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByName(ByVal name As String) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByBrandedPrescribableIds(ByVal brandedPrescribableIds As VidalUcdService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="BrandedPrescribableUcdsList")> VidalUcdService.ArrayOfBrandedPrescribableUcds
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchUcdIndicatorsByUcdIds(ByVal ucdIds As VidalUcdService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdIndicatorsList")> VidalUcdService.ArrayOfUcdIndicators
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByPackId(ByVal packId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="ucd")> VidalUcdService.ucd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByCompanyId(ByVal companyId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdList")> VidalUcdService.ArrayOfUcd
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds(ByVal ucdIds As VidalUcdService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="ucdPosologyUnitsAndItemsConcentrationsList")> VidalUcdService.ArrayOfUcdPosologyUnitsAndItemsConcentrations
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByNameWithPagedResult(ByVal name As String, ByVal marketStatuses As VidalUcdService.ArrayOfMarketStatus, ByVal pageNumber As System.Nullable(Of Integer), ByVal pageSize As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="pagedResultUcd")> VidalUcdService.pagedResultUcd
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ucdServiceChannel
        Inherits VidalUcdService.ucdService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ucdServiceClient
        Inherits System.ServiceModel.ClientBase(Of VidalUcdService.ucdService)
        Implements VidalUcdService.ucdService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function searchByIds(ByVal ucdIds As VidalUcdService.ArrayOfInt) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByIds
            Return MyBase.Channel.searchByIds(ucdIds)
        End Function
        
        Public Function getAllUcds(ByVal ucdApiFilter As System.Nullable(Of VidalUcdService.UcdApiFilter), ByVal marketStatuses As VidalUcdService.ArrayOfMarketStatus, ByVal pageNumber As System.Nullable(Of Integer), ByVal pageSize As System.Nullable(Of Integer)) As VidalUcdService.pagedResultUcd Implements VidalUcdService.ucdService.getAllUcds
            Return MyBase.Channel.getAllUcds(ucdApiFilter, marketStatuses, pageNumber, pageSize)
        End Function
        
        Public Function searchByProductRangeIds(ByVal productRangeIds As VidalUcdService.ArrayOfInt) As VidalUcdService.ArrayOfProductRangeUcdCouple Implements VidalUcdService.ucdService.searchByProductRangeIds
            Return MyBase.Channel.searchByProductRangeIds(productRangeIds)
        End Function
        
        Public Function searchByProductId(ByVal productId As System.Nullable(Of Integer)) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByProductId
            Return MyBase.Channel.searchByProductId(productId)
        End Function
        
        Public Function searchByCommonNameGroupId(ByVal commonNameGroupId As System.Nullable(Of Integer)) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByCommonNameGroupId
            Return MyBase.Channel.searchByCommonNameGroupId(commonNameGroupId)
        End Function
        
        Public Function searchById(ByVal ucdId As System.Nullable(Of Integer)) As VidalUcdService.ucd Implements VidalUcdService.ucdService.searchById
            Return MyBase.Channel.searchById(ucdId)
        End Function
        
        Public Function searchByCodes(ByVal codes As VidalUcdService.ArrayOfString) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByCodes
            Return MyBase.Channel.searchByCodes(codes)
        End Function
        
        Public Function searchNewlyAvailableUcds() As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchNewlyAvailableUcds
            Return MyBase.Channel.searchNewlyAvailableUcds
        End Function
        
        Public Function searchByCode(ByVal code As String) As VidalUcdService.ucd Implements VidalUcdService.ucdService.searchByCode
            Return MyBase.Channel.searchByCode(code)
        End Function
        
        Public Function searchByCompanyIdAndType(ByVal companyId As System.Nullable(Of Integer), ByVal type As System.Nullable(Of VidalUcdService.CompanyType)) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByCompanyIdAndType
            Return MyBase.Channel.searchByCompanyIdAndType(companyId, type)
        End Function
        
        Public Function searchByName(ByVal name As String) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByName
            Return MyBase.Channel.searchByName(name)
        End Function
        
        Public Function searchByBrandedPrescribableIds(ByVal brandedPrescribableIds As VidalUcdService.ArrayOfInt) As VidalUcdService.ArrayOfBrandedPrescribableUcds Implements VidalUcdService.ucdService.searchByBrandedPrescribableIds
            Return MyBase.Channel.searchByBrandedPrescribableIds(brandedPrescribableIds)
        End Function
        
        Public Function searchUcdIndicatorsByUcdIds(ByVal ucdIds As VidalUcdService.ArrayOfInt) As VidalUcdService.ArrayOfUcdIndicators Implements VidalUcdService.ucdService.searchUcdIndicatorsByUcdIds
            Return MyBase.Channel.searchUcdIndicatorsByUcdIds(ucdIds)
        End Function
        
        Public Function searchByPackId(ByVal packId As System.Nullable(Of Integer)) As VidalUcdService.ucd Implements VidalUcdService.ucdService.searchByPackId
            Return MyBase.Channel.searchByPackId(packId)
        End Function
        
        Public Function searchByCompanyId(ByVal companyId As System.Nullable(Of Integer)) As VidalUcdService.ArrayOfUcd Implements VidalUcdService.ucdService.searchByCompanyId
            Return MyBase.Channel.searchByCompanyId(companyId)
        End Function
        
        Public Function getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds(ByVal ucdIds As VidalUcdService.ArrayOfInt) As VidalUcdService.ArrayOfUcdPosologyUnitsAndItemsConcentrations Implements VidalUcdService.ucdService.getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds
            Return MyBase.Channel.getUcdsPosologyUnitsAndItemsConcentrationsByUcdIds(ucdIds)
        End Function
        
        Public Function searchByNameWithPagedResult(ByVal name As String, ByVal marketStatuses As VidalUcdService.ArrayOfMarketStatus, ByVal pageNumber As System.Nullable(Of Integer), ByVal pageSize As System.Nullable(Of Integer)) As VidalUcdService.pagedResultUcd Implements VidalUcdService.ucdService.searchByNameWithPagedResult
            Return MyBase.Channel.searchByNameWithPagedResult(name, marketStatuses, pageNumber, pageSize)
        End Function
    End Class
End Namespace
