'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.17929
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace VidalCNGService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfInt", [Namespace]:="urn:Vidal", ItemName:="int"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfInt
        Inherits System.Collections.Generic.List(Of System.Nullable(Of Integer))
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfCommonNameGroupIndicators", [Namespace]:="urn:Vidal", ItemName:="commonNameGroupIndicators"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfCommonNameGroupIndicators
        Inherits System.Collections.Generic.List(Of VidalCNGService.commonNameGroupIndicators)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="commonNameGroupIndicators", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class commonNameGroupIndicators
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private commonNameGroupField As VidalCNGService.commonNameGroup
        
        Private indicatorsField As VidalCNGService.ArrayOfIndicator
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property commonNameGroup() As VidalCNGService.commonNameGroup
            Get
                Return Me.commonNameGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.commonNameGroupField, value) <> true) Then
                    Me.commonNameGroupField = value
                    Me.RaisePropertyChanged("commonNameGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property indicators() As VidalCNGService.ArrayOfIndicator
            Get
                Return Me.indicatorsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.indicatorsField, value) <> true) Then
                    Me.indicatorsField = value
                    Me.RaisePropertyChanged("indicators")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="commonNameGroup", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class commonNameGroup
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private maxUcdRangePriceField As System.Nullable(Of Single)
        
        Private minUcdRangePriceField As System.Nullable(Of Single)
        
        Private nameField As String
        
        Private notHomogeneousByInteractionsField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property maxUcdRangePrice() As System.Nullable(Of Single)
            Get
                Return Me.maxUcdRangePriceField
            End Get
            Set
                If (Me.maxUcdRangePriceField.Equals(value) <> true) Then
                    Me.maxUcdRangePriceField = value
                    Me.RaisePropertyChanged("maxUcdRangePrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property minUcdRangePrice() As System.Nullable(Of Single)
            Get
                Return Me.minUcdRangePriceField
            End Get
            Set
                If (Me.minUcdRangePriceField.Equals(value) <> true) Then
                    Me.minUcdRangePriceField = value
                    Me.RaisePropertyChanged("minUcdRangePrice")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property notHomogeneousByInteractions() As Boolean
            Get
                Return Me.notHomogeneousByInteractionsField
            End Get
            Set
                If (Me.notHomogeneousByInteractionsField.Equals(value) <> true) Then
                    Me.notHomogeneousByInteractionsField = value
                    Me.RaisePropertyChanged("notHomogeneousByInteractions")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfIndicator", [Namespace]:="urn:Vidal", ItemName:="indicator"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfIndicator
        Inherits System.Collections.Generic.List(Of VidalCNGService.indicator)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="indicator", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class indicator
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private indicatorValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property indicatorValue() As String
            Get
                Return Me.indicatorValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.indicatorValueField, value) <> true) Then
                    Me.indicatorValueField = value
                    Me.RaisePropertyChanged("indicatorValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfCommonNameGroup", [Namespace]:="urn:Vidal", ItemName:="commonNameGroup"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfCommonNameGroup
        Inherits System.Collections.Generic.List(Of VidalCNGService.commonNameGroup)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GalenicForm", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GalenicForm
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        Private parentIdField As System.Nullable(Of Integer)
        
        Private searchField As Boolean
        
        Private shortNameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property parentId() As System.Nullable(Of Integer)
            Get
                Return Me.parentIdField
            End Get
            Set
                If (Me.parentIdField.Equals(value) <> true) Then
                    Me.parentIdField = value
                    Me.RaisePropertyChanged("parentId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property search() As Boolean
            Get
                Return Me.searchField
            End Get
            Set
                If (Me.searchField.Equals(value) <> true) Then
                    Me.searchField = value
                    Me.RaisePropertyChanged("search")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property shortName() As String
            Get
                Return Me.shortNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.shortNameField, value) <> true) Then
                    Me.shortNameField = value
                    Me.RaisePropertyChanged("shortName")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfRoute", [Namespace]:="urn:Vidal", ItemName:="route"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfRoute
        Inherits System.Collections.Generic.List(Of VidalCNGService.route)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="route", [Namespace]:="urn:Vidal"),  _
     System.SerializableAttribute()>  _
    Partial Public Class route
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private idField As System.Nullable(Of Integer)
        
        Private nameField As String
        
        Private parentIdField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property id() As System.Nullable(Of Integer)
            Get
                Return Me.idField
            End Get
            Set
                If (Me.idField.Equals(value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property parentId() As System.Nullable(Of Integer)
            Get
                Return Me.parentIdField
            End Get
            Set
                If (Me.parentIdField.Equals(value) <> true) Then
                    Me.parentIdField = value
                    Me.RaisePropertyChanged("parentId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:Vidal", ConfigurationName:="VidalCNGService.commonNameGroupService")>  _
    Public Interface commonNameGroupService
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchCommonNameGroupIndicatorsByCommonNameGroupIds(ByVal commonNameGroupIds As VidalCNGService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupIndicatorsList")> VidalCNGService.ArrayOfCommonNameGroupIndicators
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByIds(ByVal commonNameGroupIds As VidalCNGService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupList")> VidalCNGService.ArrayOfCommonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByUcdId(ByVal ucdId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupList")> VidalCNGService.ArrayOfCommonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByAtcIds(ByVal atcIds As VidalCNGService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupList")> VidalCNGService.ArrayOfCommonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByProductId(ByVal productId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroup")> VidalCNGService.commonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByActivePrincipleIds(ByVal moleculeIds As VidalCNGService.ArrayOfInt) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupList")> VidalCNGService.ArrayOfCommonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getGalenicForm(ByVal commonNameGroupId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="galenicForm")> VidalCNGService.GalenicForm
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByName(ByVal name As String) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupList")> VidalCNGService.ArrayOfCommonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchById(ByVal commonNameGroupId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroup")> VidalCNGService.commonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByPackId(ByVal packId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroup")> VidalCNGService.commonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function searchByAtcId(ByVal atcId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="commonNameGroupList")> VidalCNGService.ArrayOfCommonNameGroup
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function getRoute(ByVal commonNameGroupId As System.Nullable(Of Integer)) As <System.ServiceModel.MessageParameterAttribute(Name:="routeList")> VidalCNGService.ArrayOfRoute
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface commonNameGroupServiceChannel
        Inherits VidalCNGService.commonNameGroupService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class commonNameGroupServiceClient
        Inherits System.ServiceModel.ClientBase(Of VidalCNGService.commonNameGroupService)
        Implements VidalCNGService.commonNameGroupService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function searchCommonNameGroupIndicatorsByCommonNameGroupIds(ByVal commonNameGroupIds As VidalCNGService.ArrayOfInt) As VidalCNGService.ArrayOfCommonNameGroupIndicators Implements VidalCNGService.commonNameGroupService.searchCommonNameGroupIndicatorsByCommonNameGroupIds
            Return MyBase.Channel.searchCommonNameGroupIndicatorsByCommonNameGroupIds(commonNameGroupIds)
        End Function
        
        Public Function searchByIds(ByVal commonNameGroupIds As VidalCNGService.ArrayOfInt) As VidalCNGService.ArrayOfCommonNameGroup Implements VidalCNGService.commonNameGroupService.searchByIds
            Return MyBase.Channel.searchByIds(commonNameGroupIds)
        End Function
        
        Public Function searchByUcdId(ByVal ucdId As System.Nullable(Of Integer)) As VidalCNGService.ArrayOfCommonNameGroup Implements VidalCNGService.commonNameGroupService.searchByUcdId
            Return MyBase.Channel.searchByUcdId(ucdId)
        End Function
        
        Public Function searchByAtcIds(ByVal atcIds As VidalCNGService.ArrayOfInt) As VidalCNGService.ArrayOfCommonNameGroup Implements VidalCNGService.commonNameGroupService.searchByAtcIds
            Return MyBase.Channel.searchByAtcIds(atcIds)
        End Function
        
        Public Function searchByProductId(ByVal productId As System.Nullable(Of Integer)) As VidalCNGService.commonNameGroup Implements VidalCNGService.commonNameGroupService.searchByProductId
            Return MyBase.Channel.searchByProductId(productId)
        End Function
        
        Public Function searchByActivePrincipleIds(ByVal moleculeIds As VidalCNGService.ArrayOfInt) As VidalCNGService.ArrayOfCommonNameGroup Implements VidalCNGService.commonNameGroupService.searchByActivePrincipleIds
            Return MyBase.Channel.searchByActivePrincipleIds(moleculeIds)
        End Function
        
        Public Function getGalenicForm(ByVal commonNameGroupId As System.Nullable(Of Integer)) As VidalCNGService.GalenicForm Implements VidalCNGService.commonNameGroupService.getGalenicForm
            Return MyBase.Channel.getGalenicForm(commonNameGroupId)
        End Function
        
        Public Function searchByName(ByVal name As String) As VidalCNGService.ArrayOfCommonNameGroup Implements VidalCNGService.commonNameGroupService.searchByName
            Return MyBase.Channel.searchByName(name)
        End Function
        
        Public Function searchById(ByVal commonNameGroupId As System.Nullable(Of Integer)) As VidalCNGService.commonNameGroup Implements VidalCNGService.commonNameGroupService.searchById
            Return MyBase.Channel.searchById(commonNameGroupId)
        End Function
        
        Public Function searchByPackId(ByVal packId As System.Nullable(Of Integer)) As VidalCNGService.commonNameGroup Implements VidalCNGService.commonNameGroupService.searchByPackId
            Return MyBase.Channel.searchByPackId(packId)
        End Function
        
        Public Function searchByAtcId(ByVal atcId As System.Nullable(Of Integer)) As VidalCNGService.ArrayOfCommonNameGroup Implements VidalCNGService.commonNameGroupService.searchByAtcId
            Return MyBase.Channel.searchByAtcId(atcId)
        End Function
        
        Public Function getRoute(ByVal commonNameGroupId As System.Nullable(Of Integer)) As VidalCNGService.ArrayOfRoute Implements VidalCNGService.commonNameGroupService.getRoute
            Return MyBase.Channel.getRoute(commonNameGroupId)
        End Function
    End Class
End Namespace
